version: "3"
services:
  clamav:
    container_name: clamav
    image: clamav:latest
    build:
      context: ./clamav-docker
    environment:
      - MAX_SCAN_SIZE=500M
      - MAX_FILE_SIZE=500M
      - MAX_STREAM_LENGTH=500M
    hostname: clamav
    restart: always 
    logging:
      driver: awslogs
      options: 
        awslogs-group: /aws/ecs/submission-scanner-processor-service
        awslogs-region: us-east-1
        awslogs-stream-prefix: clam_server     
  app:
    image: app:latest
    container_name: submission-scanner-processor
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "0:3000"
    links:
      - clamav
    environment:
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
    links:
      - clamav
    depends_on:
      - clamav
    logging:
      driver: awslogs
      options: 
        awslogs-group: /aws/ecs/submission-scanner-processor-service
        awslogs-region: us-east-1
        awslogs-stream-prefix: submission_scanner
    env_file:
      - api.env
    command: npm start  
 
