version: "3"
services:
  scanner:
    image: scanner:latest
    container_name: clamav-scanner
    environment:
      - CLAMAV_NO_MILTERD=true
    hostname: scanner
    restart: always
    build:
      context: .
      dockerfile: clamav-docker/Dockerfile
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ecs/file-scanner-processor-service
        awslogs-region: us-east-1
        awslogs-stream-prefix: clam_server
  app:
    image: app:latest
    container_name: file-scanner-processor
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "0:3000"
    links:
      - scanner
    environment:
      - CLAMAV_HOST=scanner
      - CLAMAV_PORT=3310
    depends_on:
      - scanner
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ecs/file-scanner-processor-service
        awslogs-region: us-east-1
        awslogs-stream-prefix: file_scanner
    env_file:
      - api.env
    command: npm start
